name: Terraform Deployment

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest  # Change to self-hosted if running on EC2 (see note below)
    
    env:
      GIT_BRANCH: ${{ github.ref_name }}  # Detects the branch name dynamically
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Debug Branch Name
        run: echo "✅ Current Branch Detected by GitHub Actions:$GIT_BRANCH"

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -fsSL https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        working-directory: day-1/task1&2
        run: |
          terraform init
          echo "Current Branch: $GIT_BRANCH"

      - name: Terraform Plan
        working-directory: day-1/task1&2
        run: terraform plan -out=tfplan

      - name: Approval Check (Manual Step)
        if: github.ref == 'refs/heads/main'
        run: echo "⏳ Waiting for approval in GitHub Actions UI..." && sleep 10
        timeout-minutes: 10

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: day-1/task1&2
        run: terraform apply -auto-approve tfplan

      - name: Cleanup
        if: always()
        run: echo "Pipeline execution completed."